services:
  database:
    image: mongo:latest
    container_name: weblarek-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - db:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - backend-network

  backend:
    image: 'ghcr.io/${OWNER}/weblarek-backend:v1.0.0'
    container_name: weblarek-backend
    restart: always
    environment:
      PORT: ${PORT}
      DB_ADDRESS: ${DB_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_ACCESS_TOKEN_SECRET: ${AUTH_ACCESS_TOKEN_SECRET}
      AUTH_ACCESS_TOKEN_EXPIRY: ${AUTH_ACCESS_TOKEN_EXPIRY}
      AUTH_REFRESH_TOKEN_SECRET: ${AUTH_REFRESH_TOKEN_SECRET}
      AUTH_REFRESH_TOKEN_EXPIRY: ${AUTH_REFRESH_TOKEN_EXPIRY}
      ORIGIN_ALLOW: ${ORIGIN_ALLOW}
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    ports:
      - 3000:3000
    networks:
      - backend-network
    depends_on:
      - database

  frontend:
    image: 'ghcr.io/${OWNER}/weblarek-frontend:v1.0.0'
    container_name: weblarek-frontend
    environment:
      VITE_API_ORIGIN: ${VITE_API_ORIGIN}
    volumes:
      - frontend:/app/frontend/dist
    networks:
      - frontend-network

  server:
    image: 'ghcr.io/${OWNER}/weblarek-nginx:v1.0.0'
    container_name: weblarek-nginx
    ports:
      - 81:80
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - frontend-network
      - backend-network

volumes:
  frontend:
  public:
  db:

networks:
  backend-network:
  frontend-network:
